ali-langengine-community/ali-langengine-claude/src/main/java/com/alibaba/langengine/claude/model/ClaudeChatModel.java
ali-langengine-community/ali-langengine-claude/src/main/java/com/alibaba/langengine/claude/model/ClaudeModelConstants.java
ali-langengine-community/ali-langengine-claude/src/test/java/com/alibaba/langengine/claude/model/ClaudeChatModelTest.java
ali-langengine-community/ali-langengine-tair/src/main/java/com/alibaba/langengine/tair/vectorstore/Tair.java
ali-langengine-community/ali-langengine-xinghuo/src/main/java/com/alibaba/langengine/xinghuo/WebSocketListener.java
ali-langengine-community/ali-langengine-xinghuo/src/main/java/com/alibaba/langengine/xinghuo/XinghuoConfiguration.java
ali-langengine-core/src/main/java/com/alibaba/langengine/core/agent/expert/ExpertChain.java
ali-langengine-core/src/main/java/com/alibaba/langengine/core/agent/semantickernel/planning/SequentialPlannerOutputParser.java
ali-langengine-core/src/main/java/com/alibaba/langengine/core/chain/router/RouterChain.java

Fix typos 
ClaudeModelContants.java 应为 ClaudeModelConstants.java

Fix typos 

---

.gitignore
ali-langengine-infrastructure/ali-langengine-gpt/pom.xml
ali-langengine-infrastructure/ali-langengine-gpt/src/main/java/com/alibaba/langengine/gpt/nl2sql/db/SQLEngine.java

PR tddl dependency remove 20250809

---

ali-langengine-community/ali-langengine-aliyunaisearch/pom.xml
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/AliyunAiSearchConfiguration.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/AISearchException.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/AliyunAiSearchConstant.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/ClientConfig.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/HistoryItem.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/SearchResult.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/WebSearchClient.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/WebSearchErrorResponse.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/WebSearchRequest.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/main/java/com/alibaba/langengine/aliyunaisearch/sdk/WebSearchResponse.java
ali-langengine-community/ali-langengine-aliyunaisearch/src/test/java/com/alibaba/langengine/aliyunaisearch/sdk/WebSearchClientTest.java
pom.xml

add aliyun search  on community https://github.com/AIDC-AI/Agentic-ADK/issues/24

feat(aliyunaisearch): aliyun search support

---

ali-langengine-community/ali-langengine-baidusearch/dependency.sh
ali-langengine-community/ali-langengine-baidusearch/deploy.sh
ali-langengine-community/ali-langengine-baidusearch/install.sh
ali-langengine-community/ali-langengine-baidusearch/package.sh
ali-langengine-community/ali-langengine-baidusearch/pom.xml
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/BaiduConfiguration.java
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/sdk/BaiduClient.java
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/sdk/BaiduConstant.java
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/sdk/BaiduException.java
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/sdk/SearchRequest.java
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/sdk/SearchResponse.java
ali-langengine-community/ali-langengine-baidusearch/src/main/java/com/alibaba/langengine/baidu/sdk/SearchResult.java
pom.xml

feat: add the Baidu search module and related functional implementations

---

ali-langengine-community/ali-langengine-serp/dependency.sh
ali-langengine-community/ali-langengine-serp/deploy.sh
ali-langengine-community/ali-langengine-serp/install.sh
ali-langengine-community/ali-langengine-serp/package.sh
ali-langengine-community/ali-langengine-serp/pom.xml
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/SerpConfiguration.java
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/sdk/SearchRequest.java
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/sdk/SearchResponse.java
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/sdk/SearchResult.java
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/sdk/SerpClient.java
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/sdk/SerpConstant.java
ali-langengine-community/ali-langengine-serp/src/main/java/com/alibaba/langengine/serp/sdk/SerpException.java
ali-langengine-community/ali-langengine-serp/src/test/java/com/alibaba/langengine/serp/sdk/SerpClientTest.java
ali-langengine-community/ali-langengine-serp/src/test/resources/langengine.properties
ali-langengine-community/ali-langengine-serp/src/test/resources/logback.xml
pom.xml

add serp search on community #24

feat(tools):serp support

---

ali-langengine-community/ali-langengine-googletranslate/dependency.sh
ali-langengine-community/ali-langengine-googletranslate/deploy.sh
ali-langengine-community/ali-langengine-googletranslate/install.sh
ali-langengine-community/ali-langengine-googletranslate/package.sh
ali-langengine-community/ali-langengine-googletranslate/pom.xml
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/GoogleTranslateConfiguration.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/DetectLanguageRequest.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/DetectLanguageResponse.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/GoogleTranslateClient.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/GoogleTranslateConstant.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/GoogleTranslateException.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/LanguagesResponse.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/TranslateRequest.java
ali-langengine-community/ali-langengine-googletranslate/src/main/java/com/alibaba/langengine/googletranslate/sdk/TranslateResponse.java
ali-langengine-community/ali-langengine-googletranslate/src/test/java/com/alibaba/langengine/googletranslate/sdk/GoogleTranslateClientTest.java
pom.xml

add google translate on community https://github.com/AIDC-AI/Agentic-ADK/issues/24

feat(tools):google translate support

---

ali-langengine-community/ali-langengine-elasticsearch/pom.xml
ali-langengine-community/ali-langengine-elasticsearch/src/main/java/com/alibaba/langengine/elasticsearch/ElasticsearchConfiguration.java
ali-langengine-community/ali-langengine-elasticsearch/src/main/java/com/alibaba/langengine/elasticsearch/vectorstore/Elasticsearch.java
ali-langengine-community/ali-langengine-elasticsearch/src/main/java/com/alibaba/langengine/elasticsearch/vectorstore/ElasticsearchParam.java
ali-langengine-community/ali-langengine-elasticsearch/src/main/java/com/alibaba/langengine/elasticsearch/vectorstore/ElasticsearchService.java
ali-langengine-community/ali-langengine-elasticsearch/src/test/java/com/alibaba/langengine/elasticsearch/ElasticsearchConfigurationTest.java
ali-langengine-community/ali-langengine-elasticsearch/src/test/java/com/alibaba/langengine/elasticsearch/vectorstore/ElasticsearchServiceTest.java
ali-langengine-community/ali-langengine-elasticsearch/src/test/java/com/alibaba/langengine/elasticsearch/vectorstore/ElasticsearchTest.java
pom.xml

feat(vectorstore): add new ES vectorstore

---

ali-langengine-community/ali-langengine-vespa/dependency.sh
ali-langengine-community/ali-langengine-vespa/deploy.sh
ali-langengine-community/ali-langengine-vespa/install.sh
ali-langengine-community/ali-langengine-vespa/package.sh
ali-langengine-community/ali-langengine-vespa/pom.xml
ali-langengine-community/ali-langengine-vespa/src/main/java/com/alibaba/langengine/vespa/VespaConfiguration.java
ali-langengine-community/ali-langengine-vespa/src/main/java/com/alibaba/langengine/vespa/vectorstore/Vespa.java
ali-langengine-community/ali-langengine-vespa/src/main/java/com/alibaba/langengine/vespa/vectorstore/VespaParam.java
ali-langengine-community/ali-langengine-vespa/src/main/java/com/alibaba/langengine/vespa/vectorstore/VespaService.java
ali-langengine-community/ali-langengine-vespa/src/test/java/com/alibaba/langengine/vespa/VespaConfigurationTest.java
ali-langengine-community/ali-langengine-vespa/src/test/java/com/alibaba/langengine/vespa/vectorstore/VespaServiceTest.java
ali-langengine-community/ali-langengine-vespa/src/test/java/com/alibaba/langengine/vespa/vectorstore/VespaTest.java
ali-langengine-community/ali-langengine-vespa/src/test/resources/langengine.properties
ali-langengine-community/ali-langengine-vespa/src/test/resources/logback.xml
pom.xml

feat(vectorstore): add new vespa

---

ali-langengine-community/ali-langengine-marqo/dependency.sh
ali-langengine-community/ali-langengine-marqo/deploy.sh
ali-langengine-community/ali-langengine-marqo/install.sh
ali-langengine-community/ali-langengine-marqo/package.sh
ali-langengine-community/ali-langengine-marqo/pom.xml
ali-langengine-community/ali-langengine-marqo/src/main/java/com/alibaba/langengine/marqo/MarqoConfiguration.java
ali-langengine-community/ali-langengine-marqo/src/main/java/com/alibaba/langengine/marqo/vectorstore/Marqo.java
ali-langengine-community/ali-langengine-marqo/src/main/java/com/alibaba/langengine/marqo/vectorstore/MarqoParam.java
ali-langengine-community/ali-langengine-marqo/src/main/java/com/alibaba/langengine/marqo/vectorstore/MarqoService.java
ali-langengine-community/ali-langengine-marqo/src/test/java/com/alibaba/langengine/marqo/vectorstore/MarqoIntegrationTest.java
ali-langengine-community/ali-langengine-marqo/src/test/java/com/alibaba/langengine/marqo/vectorstore/MarqoServiceTest.java
ali-langengine-community/ali-langengine-marqo/src/test/java/com/alibaba/langengine/marqo/vectorstore/MarqoTest.java
pom.xml

feat(vectorstore): add new Marqo

---

ali-langengine-community/ali-langengine-ollama/dependency.sh
ali-langengine-community/ali-langengine-ollama/deploy.sh
ali-langengine-community/ali-langengine-ollama/install.sh
ali-langengine-community/ali-langengine-ollama/package.sh
ali-langengine-community/ali-langengine-ollama/pom.xml
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/OllamaConfiguration.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/ChatRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/ChatResponse.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/CopyRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/CreateRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/DeleteRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/GenerateRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/GenerateResponse.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/ModelsResponse.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/OllamaClient.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/OllamaConstant.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/OllamaException.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/OllamaRequestBuilder.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/OllamaStreamCallback.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/PullRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/ShowRequest.java
ali-langengine-community/ali-langengine-ollama/src/main/java/com/alibaba/langengine/ollama/sdk/ShowResponse.java
ali-langengine-community/ali-langengine-ollama/src/test/java/com/alibaba/langengine/ollama/sdk/OllamaClientTest.java
ali-langengine-community/ali-langengine-ollama/src/test/resources/langengine.properties
ali-langengine-community/ali-langengine-ollama/src/test/resources/logback.xml
ali-langengine-infrastructure/ali-langengine-docloader/src/main/java/com/alibaba/langengine/docloader/notion/NotionUserDocLoader.java
pom.xml

add ollama and notion docloader  on community https://github.com/AIDC-AI/Agentic-ADK/issues/24

feat(tools):ollama and notion docloader support

---

ali-langengine-community/ali-langengine-reddit/pom.xml
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/RedditConfiguration.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditClient.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditException.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditPost.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditSearchRequest.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditSearchResponse.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/vectorstore/RedditVectorStore.java
ali-langengine-community/ali-langengine-reddit/src/test/java/com/alibaba/langengine/reddit/sdk/RedditClientTest.java
ali-langengine-community/ali-langengine-reddit/src/test/java/com/alibaba/langengine/reddit/vectorstore/RedditVectorStoreTest.java

feat(tools): add new reddit search

---

ali-langengine-community/ali-langengine-reddit/pom.xml
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/RedditConfiguration.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditClient.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/sdk/RedditPost.java
ali-langengine-community/ali-langengine-reddit/src/main/java/com/alibaba/langengine/reddit/vectorstore/RedditVectorStore.java
ali-langengine-community/ali-langengine-reddit/src/test/java/com/alibaba/langengine/reddit/vectorstore/RedditVectorStoreTest.java

feat(tools): enhance reddit search

---

ali-langengine-community/ali-langengine-jina/dependency.sh
ali-langengine-community/ali-langengine-jina/deploy.sh
ali-langengine-community/ali-langengine-jina/install.sh
ali-langengine-community/ali-langengine-jina/package.sh
ali-langengine-community/ali-langengine-jina/pom.xml
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/JinaConfiguration.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/JinaClient.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/JinaConstant.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/JinaException.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/JinaService.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/Usage.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/ClassifierRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/DeepSearchRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/EmbeddingsRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/ReaderRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/RerankRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/SearchRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/request/SegmenterRequest.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/ClassifierResponse.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/DeepSearchResponse.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/EmbeddingsResponse.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/ReaderResponse.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/RerankResponse.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/SearchResponse.java
ali-langengine-community/ali-langengine-jina/src/main/java/com/alibaba/langengine/jina/sdk/response/SegmenterResponse.java
ali-langengine-community/ali-langengine-jina/src/test/java/com/alibaba/langengine/jina/JinaClientTest.java
ali-langengine-community/ali-langengine-jina/src/test/java/com/alibaba/langengine/jina/JinaServiceTest.java
pom.xml

Issue #24.
The response time of that deep search API sometimes exceeds the default time limit, so it is marked as Disabled in the unit test class. Users can configure a longer timeout duration in actual use.

feat(community): add jina ai support

---

ali-langengine-community/ali-langengine-pubmed/pom.xml
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/PubMedClient.java
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/PubMedConfiguration.java
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/PubMedException.java
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/PubMedVectorStore.java
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/model/PubMedArticle.java
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/model/PubMedSearchRequest.java
ali-langengine-community/ali-langengine-pubmed/src/main/java/com/alibaba/langengine/pubmed/model/PubMedSearchResponse.java
ali-langengine-community/ali-langengine-pubmed/src/test/java/com/alibaba/langengine/pubmed/PubMedConfigurationTest.java
ali-langengine-community/ali-langengine-pubmed/src/test/java/com/alibaba/langengine/pubmed/PubMedExceptionTest.java
ali-langengine-community/ali-langengine-pubmed/src/test/java/com/alibaba/langengine/pubmed/model/PubMedArticleTest.java
ali-langengine-community/ali-langengine-pubmed/src/test/java/com/alibaba/langengine/pubmed/model/PubMedSearchRequestTest.java
ali-langengine-core/src/main/java/com/alibaba/langengine/core/util/VectorUtils.java

feat(tools): add PubMed Search

---

ali-langengine-community/ali-langengine-lancedb/dependency.sh
ali-langengine-community/ali-langengine-lancedb/deploy.sh
ali-langengine-community/ali-langengine-lancedb/install.sh
ali-langengine-community/ali-langengine-lancedb/package.sh
ali-langengine-community/ali-langengine-lancedb/pom.xml
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/LanceDbConfiguration.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/LanceDbException.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/client/LanceDbClient.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/model/LanceDbQueryRequest.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/model/LanceDbQueryResponse.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/model/LanceDbVector.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/vectorstore/LanceDbParam.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/vectorstore/LanceDbService.java
ali-langengine-community/ali-langengine-lancedb/src/main/java/com/alibaba/langengine/lancedb/vectorstore/LanceDbVectorStore.java
ali-langengine-community/ali-langengine-lancedb/src/test/java/com/alibaba/langengine/lancedb/LanceDbBasicTest.java
ali-langengine-community/ali-langengine-lancedb/src/test/java/com/alibaba/langengine/lancedb/LanceDbIntegrationTest.java
ali-langengine-community/ali-langengine-lancedb/src/test/java/com/alibaba/langengine/lancedb/LanceDbVectorStoreTest.java

feat(vectorstore) add new LanceDB

---

ali-langengine-community/ali-langengine-metaso/dependency.sh
ali-langengine-community/ali-langengine-metaso/deploy.sh
ali-langengine-community/ali-langengine-metaso/install.sh
ali-langengine-community/ali-langengine-metaso/package.sh
ali-langengine-community/ali-langengine-metaso/pom.xml
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/MetaSoConfiguration.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/MetaSoClient.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/MetaSoConstant.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/MetaSoException.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/QARequest.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/QAResponse.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/SearchRequest.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/SearchResponse.java
ali-langengine-community/ali-langengine-metaso/src/main/java/com/alibaba/langengine/metaso/sdk/SearchResult.java
ali-langengine-community/ali-langengine-metaso/src/test/java/com/alibaba/langengine/metaso/sdk/MetaSoClientTest.java
ali-langengine-community/ali-langengine-metaso/src/test/resources/langengine.properties
ali-langengine-community/ali-langengine-metaso/src/test/resources/logback.xml
pom.xml

add metaso on community https://github.com/AIDC-AI/Agentic-ADK/issues/24

feat(tools):metaso support

---

ali-langengine-community/ali-langengine-googlesearch/dependency.sh
ali-langengine-community/ali-langengine-googlesearch/deploy.sh
ali-langengine-community/ali-langengine-googlesearch/install.sh
ali-langengine-community/ali-langengine-googlesearch/package.sh
ali-langengine-community/ali-langengine-googlesearch/pom.xml
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/GoogleSearchConfiguration.java
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/sdk/GoogleClient.java
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/sdk/GoogleConstant.java
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/sdk/GoogleException.java
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/sdk/SearchRequest.java
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/sdk/SearchResponse.java
ali-langengine-community/ali-langengine-googlesearch/src/main/java/com/alibaba/langengine/google/sdk/SearchResult.java
ali-langengine-community/ali-langengine-googlesearch/src/test/java/com/alibaba/langengine/google/GoogleClientTest.java
pom.xml

add Google serach tool

---

ali-langengine-community/ali-langengine-amap/src/main/java/com/alibaba/langengine/amap/sdk/AMapClient.java
ali-langengine-community/ali-langengine-amap/src/main/java/com/alibaba/langengine/amap/sdk/AMapConstant.java
ali-langengine-community/ali-langengine-amap/src/main/java/com/alibaba/langengine/amap/sdk/request/PlaceSearchRequest.java
ali-langengine-community/ali-langengine-amap/src/main/java/com/alibaba/langengine/amap/sdk/request/WeatherRequest.java
ali-langengine-community/ali-langengine-amap/src/main/java/com/alibaba/langengine/amap/sdk/response/PlaceSearchResponse.java
ali-langengine-community/ali-langengine-amap/src/main/java/com/alibaba/langengine/amap/sdk/response/WeatherResponse.java
ali-langengine-community/ali-langengine-amap/src/test/java/com/alibaba/langengine/amap/AMapClientTest.java
ali-langengine-community/ali-langengine-baidumap/src/main/java/com/alibaba/langengine/baidumap/sdk/BaiduMapClient.java
ali-langengine-community/ali-langengine-baidumap/src/main/java/com/alibaba/langengine/baidumap/sdk/BaiduMapConstant.java
ali-langengine-community/ali-langengine-baidumap/src/main/java/com/alibaba/langengine/baidumap/sdk/request/PlaceSearchRequest.java
ali-langengine-community/ali-langengine-baidumap/src/main/java/com/alibaba/langengine/baidumap/sdk/request/WeatherRequest.java
ali-langengine-community/ali-langengine-baidumap/src/main/java/com/alibaba/langengine/baidumap/sdk/response/PlaceSearchResponse.java
ali-langengine-community/ali-langengine-baidumap/src/main/java/com/alibaba/langengine/baidumap/sdk/response/WeatherResponse.java
ali-langengine-community/ali-langengine-baidumap/src/test/java/com/alibaba/langengine/baidumap/BaiduMapClientTest.java
ali-langengine-community/ali-langengine-tencentmap/src/main/java/com/alibaba/langengine/tencentmap/sdk/TencentMapClient.java
ali-langengine-community/ali-langengine-tencentmap/src/main/java/com/alibaba/langengine/tencentmap/sdk/TencentMapConstant.java
ali-langengine-community/ali-langengine-tencentmap/src/main/java/com/alibaba/langengine/tencentmap/sdk/request/PlaceSearchRequest.java
ali-langengine-community/ali-langengine-tencentmap/src/main/java/com/alibaba/langengine/tencentmap/sdk/request/WeatherRequest.java
ali-langengine-community/ali-langengine-tencentmap/src/main/java/com/alibaba/langengine/tencentmap/sdk/response/PlaceSearchResponse.java
ali-langengine-community/ali-langengine-tencentmap/src/main/java/com/alibaba/langengine/tencentmap/sdk/response/WeatherResponse.java
ali-langengine-community/ali-langengine-tencentmap/src/test/java/com/alibaba/langengine/tencentmap/TencentMapClientTest.java

feat(tool): add weather api of 3 map tools

---

ali-langengine-community/ali-langengine-slack/dependency.sh
ali-langengine-community/ali-langengine-slack/install.sh
ali-langengine-community/ali-langengine-slack/package.sh
ali-langengine-community/ali-langengine-slack/pom.xml
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/SlackConfiguration.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/client/SlackClient.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/handler/SlackSocketModeHandler.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/model/SlackChannel.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/model/SlackMessage.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/model/SlackUser.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/tool/SlackFindChannelTool.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/tool/SlackGetChannelHistoryTool.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/tool/SlackGetChannelsTool.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/tool/SlackGetUsersTool.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/tool/SlackSendMessageTool.java
ali-langengine-community/ali-langengine-slack/src/main/java/com/alibaba/langengine/slack/tool/SlackToolLoaders.java
ali-langengine-community/ali-langengine-slack/src/test/java/com/alibaba/langengine/slack/client/SlackClientTest.java
ali-langengine-community/ali-langengine-slack/src/test/java/com/alibaba/langengine/slack/model/SlackChannelTest.java
ali-langengine-community/ali-langengine-slack/src/test/java/com/alibaba/langengine/slack/model/SlackMessageTest.java
ali-langengine-community/ali-langengine-slack/src/test/java/com/alibaba/langengine/slack/model/SlackUserTest.java

feat(tool): add Slack tools

---

ali-langengine-community/ali-langengine-notion/pom.xml
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/NotionConfiguration.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/NotionToolFactory.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/client/NotionClient.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/examples/NotionToolsExample.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/exception/NotionException.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionBlocksResult.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionDatabase.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionPage.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionPageResult.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionQueryResult.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionSearchResult.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionUser.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/model/NotionUsersResult.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/NotionContentManageTool.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/NotionDatabaseQueryTool.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/NotionPageContentTool.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/NotionPageCreateTool.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/NotionSearchTool.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/schema/NotionContentManageSchema.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/schema/NotionDatabaseQuerySchema.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/schema/NotionPageContentSchema.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/schema/NotionPageCreateSchema.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/schema/NotionPageUpdateSchema.java
ali-langengine-community/ali-langengine-notion/src/main/java/com/alibaba/langengine/notion/tools/schema/NotionSearchSchema.java
ali-langengine-community/ali-langengine-notion/src/test/java/com/alibaba/langengine/notion/NotionConfigurationTest.java
ali-langengine-community/ali-langengine-notion/src/test/java/com/alibaba/langengine/notion/factory/NotionToolFactoryTest.java
pom.xml

feat(tool): add notion tools

---

ali-langengine-community/ali-langengine-trello/pom.xml
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/TrelloConfiguration.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/TrelloToolFactory.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/client/TrelloClient.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/exception/TrelloException.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/model/TrelloBoard.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/model/TrelloCard.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/model/TrelloLabel.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/model/TrelloList.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/model/TrelloMember.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/tools/TrelloBoardOperationTool.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/tools/TrelloCardManageTool.java
ali-langengine-community/ali-langengine-trello/src/main/java/com/alibaba/langengine/trello/tools/TrelloTeamCollaborationTool.java
ali-langengine-community/ali-langengine-trello/src/test/java/com/alibaba/langengine/trello/TrelloModuleIntegrationTest.java
pom.xml

feat(tool): add Trello tools

---

ali-langengine-community/ali-langengine-jieyue/pom.xml
ali-langengine-community/ali-langengine-jieyue/src/main/java/com/alibaba/langengine/jieyue/JieYueConfiguration.java
ali-langengine-community/ali-langengine-jieyue/src/main/java/com/alibaba/langengine/jieyue/JieYueModelConstant.java
ali-langengine-community/ali-langengine-jieyue/src/main/java/com/alibaba/langengine/jieyue/model/JieYueChatModel.java
ali-langengine-community/ali-langengine-jieyue/src/main/resources/langengine.properties
ali-langengine-community/ali-langengine-jieyue/src/test/java/com/alibaba/langengine/jieyue/model/JieYueChatModelTest.java
ali-langengine-community/ali-langengine-jieyue/src/test/resources/langengine.properties
pom.xml

This PR adds support for jieyuexingchen(阶跃星辰)LLM service integration.
Please feel free to let me know if there are any issues or improvements needed. I greatly appreciate your feedback and guidance!

feat(LLM):add jieyuexingchen model service

---

ali-langengine-community/ali-langengine-perplexity/pom.xml
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/PerplexityConfiguration.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/Choice.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/Message.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/MessageContentPart.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/PerplexityClient.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/PerplexityConstant.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/PerplexityException.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/PerplexityModelConstant.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/SearchResult.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/UsageInfo.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/request/AsyncChatCompletionRequest.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/request/AsyncListRequest.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/request/ChatCompletionRequest.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/request/WebSearchOptions.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/response/AsyncJobResponse.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/response/AsyncJobSummary.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/response/AsyncListResponse.java
ali-langengine-community/ali-langengine-perplexity/src/main/java/com/alibaba/langengine/perplexity/sdk/response/ChatCompletionResponse.java
ali-langengine-community/ali-langengine-perplexity/src/main/resources/perplexity.properties.example
ali-langengine-community/ali-langengine-perplexity/src/test/java/com/alibaba/langengine/perplexity/sdk/ConfigurationDebugTest.java
ali-langengine-community/ali-langengine-perplexity/src/test/java/com/alibaba/langengine/perplexity/sdk/PerplexityClientTest.java
ali-langengine-community/ali-langengine-perplexity/src/test/resources/application.properties
pom.xml

This PR adds support for Perplexity AI search service，including both synchronous and asynchronous API support .
please feel free to let me know if there are any issues or improvements needed. I greatly appreciate your feedback and guidance.

feat:add perplexity ai search

---

ali-langengine-community/ali-langengine-sqlexecutor/README-zh.md
ali-langengine-community/ali-langengine-sqlexecutor/README.md
ali-langengine-community/ali-langengine-sqlexecutor/dependency.sh
ali-langengine-community/ali-langengine-sqlexecutor/deploy.sh
ali-langengine-community/ali-langengine-sqlexecutor/install.sh
ali-langengine-community/ali-langengine-sqlexecutor/package.sh
ali-langengine-community/ali-langengine-sqlexecutor/pom.xml
ali-langengine-community/ali-langengine-sqlexecutor/src/main/java/com/alibaba/langengine/sqlexecutor/NamedParamCompiler.java
ali-langengine-community/ali-langengine-sqlexecutor/src/main/java/com/alibaba/langengine/sqlexecutor/SafeSql.java
ali-langengine-community/ali-langengine-sqlexecutor/src/main/java/com/alibaba/langengine/sqlexecutor/SqlExecuteParams.java
ali-langengine-community/ali-langengine-sqlexecutor/src/main/java/com/alibaba/langengine/sqlexecutor/SqlExecuteResult.java
ali-langengine-community/ali-langengine-sqlexecutor/src/main/java/com/alibaba/langengine/sqlexecutor/SqlExecuteTool.java
ali-langengine-community/ali-langengine-sqlexecutor/src/test/java/com/alibaba/langengine/sqlexecutor/SqlExecuteToolTest.java
ali-langengine-community/ali-langengine-sqlexecutor/src/test/java/com/alibaba/langengine/sqlexecutor/examples/ExecutorExample.java
pom.xml

This is my first PR to this repository.  
If there are any issues with code style, structure, or contribution guidelines that I missed,  
please kindly let me know and I will be happy to adjust.
from #24

feat(tool): add SQL Interpreter

---

ali-langengine-community/ali-langengine-siliconflow/pom.xml
ali-langengine-community/ali-langengine-siliconflow/src/main/java/com/alibaba/langengine/siliconflow/Main.java
ali-langengine-community/ali-langengine-siliconflow/src/main/java/com/alibaba/langengine/siliconflow/SiliconFlowConfiguration.java
ali-langengine-community/ali-langengine-siliconflow/src/main/java/com/alibaba/langengine/siliconflow/model/SiliconFlowChatModel.java
ali-langengine-community/ali-langengine-siliconflow/src/main/java/com/alibaba/langengine/siliconflow/model/SiliconFlowModelConstants.java
ali-langengine-community/ali-langengine-siliconflow/src/main/resources/siliconflow-config.properties
ali-langengine-community/ali-langengine-siliconflow/src/test/java/com/alibaba/langengine/siliconflow/SiliconFlowTest.java
ali-langengine-community/ali-langengine-siliconflow/src/test/resources/langengine.properties
pom.xml

This PR contains support for siliconflow models support.please feel free to let me know if there are any issues or improvements needed. I greatly appreciate your feedback and guidance.

feat:add siliconflow models support

---

ali-langengine-community/ali-langengine-cxxexecutor/README-zh.md
ali-langengine-community/ali-langengine-cxxexecutor/README.md
ali-langengine-community/ali-langengine-cxxexecutor/dependency.sh
ali-langengine-community/ali-langengine-cxxexecutor/deploy.sh
ali-langengine-community/ali-langengine-cxxexecutor/install.sh
ali-langengine-community/ali-langengine-cxxexecutor/package.sh
ali-langengine-community/ali-langengine-cxxexecutor/pom.xml
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/Backend.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/CxxBackendDetector.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/CxxExecutionOptions.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/CxxExecutionPolicy.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/CxxExecutionResult.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/CxxExecutor.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/NsjailSandbox.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/ProcessUtils.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/SourceGuards.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/WasmToolchain.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/autoconfig/CxxExecutionProperties.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/java/com/alibaba/langengine/cxxexecutor/autoconfig/CxxExecutorAutoConfiguration.java
ali-langengine-community/ali-langengine-cxxexecutor/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
ali-langengine-community/ali-langengine-cxxexecutor/src/test/java/com/alibaba/langengine/cxxexecutor/CxxExecutorNsjailTests.java
ali-langengine-community/ali-langengine-cxxexecutor/src/test/java/com/alibaba/langengine/cxxexecutor/CxxExecutorWasiTests.java
ali-langengine-community/ali-langengine-cxxexecutor/src/test/java/com/alibaba/langengine/cxxexecutor/TestSupport.java
ali-langengine-community/ali-langengine-cxxexecutor/src/test/java/com/alibaba/langengine/cxxexecutor/example/ExampleMain.java
pom.xml

Feat: add c/c++ executor

---

ali-agentic-adk-python/src/ali_agentic_adk_python/core/model/bailian_llm.py
ali-agentic-adk-python/src/ali_agentic_adk_python/core/tool/bailian_app_tool.py

增加百炼应用调用，网页上显示是百炼应用，使用的是dashscope api
https://bailian.console.aliyun.com/?tab=api#/api/?type=app&url=2782167

add bailian

---

ali-langengine/ali-langengine-community/ali-langengine-hugegraph/pom.xml
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/HugeGraphConfiguration.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/client/HugeGraphClient.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/exception/HugeGraphVectorStoreException.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/model/HugeGraphQueryRequest.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/model/HugeGraphQueryResponse.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/model/HugeGraphVector.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraph.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraphParam.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraphService.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/main/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraphSimilarityFunction.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/test/java/com/alibaba/langengine/hugegraph/client/HugeGraphClientTest.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/test/java/com/alibaba/langengine/hugegraph/integration/HugeGraphIntegrationTest.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/test/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraphParamTest.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/test/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraphServiceTest.java
ali-langengine/ali-langengine-community/ali-langengine-hugegraph/src/test/java/com/alibaba/langengine/hugegraph/vectorstore/HugeGraphSimilarityFunctionTest.java
ali-langengine/pom.xml

feat(vecotrstore):add HugeGraph

---

ali-agentic-adk-java/ali-agentic-adk-extension/ali-agentic-example/src/test/java/com/alibaba/agentic/example/DeepSearchAgentTest.java

testSimpleQuestionAnswering():测试代理处理简单问题的能力，验证它可以直接回答不需要搜索的问题。
testSearchEvaluation():测试搜索结果评估功能，验证代理能够评估搜索结果的质量并记录不良请求。
testParseLlmResult():测试LLM结果解析功能，验证DeepSearchAgent能够正确解析来自LLM的不同类型响应（搜索、思考、直接结果）。
testMaxIterationLimit():测试循环限制功能，验证代理在达到最大迭代次数时能正确抛出异常。

增加了DeepSearchAgentTest的测试用例

---

ali-langengine/ali-langengine-core/pom.xml
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/impl/HierarchicalMemory.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/impl/LongTermMemory.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/impl/MediumTermMemory.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/impl/ShortTermMemory.java
ali-langengine/ali-langengine-core/src/test/java/com/alibaba/langengine/core/memory/HierarchicalMemoryTest.java

本次提交实现完整的层次化记忆策略，包括短期、中期、长期三层记忆架构。
**核心功能**:
- ✅ 滑动窗口机制，保留最近N条对话
- ✅ 快速内存访问
- ✅ 自动淘汰旧消息
- ✅ 支持向中期记忆迁移
**关键方法**:
- `buffer(String sessionId)` - 获取窗口内的记忆
- `shouldMigrate(String sessionId)` - 判断是否需要迁移
- `getMessagesToMigrate(String sessionId)` - 获取待迁移消息
- `clearMigratedMessages(String sessionId)` - 清除已迁移消息
**核心功能**:
- ✅ LLM摘要生成
- ✅ 重要性评估算法（多维度）
- ✅ 智能过滤低重要性对话
- ✅ 支持向长期记忆迁移
**重要性评估维度**:
1. 对话长度权重
2. 内容丰富度权重
3. 问答特征权重
**关键方法**:
- `migrateFromShortTerm()` - 从短期记忆迁移
- `evaluateImportance()` - 评估对话重要性
- `generateSummary()` - 生成对话摘要
- `shouldMigrateToLongTerm()` - 判断是否迁移到长期记忆
**核心功能**:
- ✅ 向量数据库存储
- ✅ 语义相似度检索
- ✅ 时间衰减机制
- ✅ 主题搜索功能
**时间衰减公式**:
```
权重 = decayFactor ^ (天数)
```
**关键方法**:
- `migrateFromMediumTerm()` - 从中期记忆迁移
- `applyTimeDecay()` - 应用时间衰减
- `searchByTopic()` - 主题搜索
- …

# 添加层次化记忆系统

---

ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/graph/Entity.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/graph/GraphStore.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/graph/InMemoryGraphStore.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/graph/KnowledgeExtractor.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/graph/Relation.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/graph/SubGraph.java
ali-langengine/ali-langengine-core/src/main/java/com/alibaba/langengine/core/memory/impl/KnowledgeGraphMemory.java
ali-langengine/ali-langengine-core/src/test/java/com/alibaba/langengine/core/memory/KnowledgeGraphMemoryTest.java

实现了基于图结构的知识存储和检索系统，支持从对话中自动抽取实体-关系知识并进行复杂推理。
- Entity: 知识图谱节点，支持重要性评分和引用计数
- Relation: 知识图谱边，支持权重管理和时间衰减
- SubGraph: 子图辅助类，支持自然语言转换
- GraphStore: 图谱存储接口，定义标准CRUD和遍历操作
- InMemoryGraphStore: 高性能内存图谱存储实现，包含多级索引优化
- KnowledgeExtractor: 知识抽取器，支持LLM和规则两种抽取模式
- KnowledgeGraphMemory: 知识图谱记忆主控制器
- ✅ 自动知识抽取：从对话中识别实体和关系（支持LLM和规则模式）
- ✅ 图遍历查询：子图提取、最短路径查找、邻居查询
- ✅ 时间衰减机制：关系权重随时间自动衰减
- ✅ 弱关系修剪：自动清理低权重关系，维护图谱健康
- ✅ 重要性评估：基于引用次数的实体重要性评分
- ✅ 多索引优化：实体关系索引、类型索引、关系类型索引
- ✅ Builder模式：灵活的配置和扩展支持
关联Issue
- #29 记忆系统能力贡献

feat: 添加知识图谱记忆系统（KnowledgeGraphMemory）

---

ali-langengine/ali-langengine-community/ali-langengine-expedia/README.md
ali-langengine/ali-langengine-community/ali-langengine-expedia/pom.xml
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/ExpediaConfiguration.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/model/CarRental.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/model/Flight.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/model/Hotel.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/service/ExpediaClient.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/service/ExpediaException.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/tool/ExpediaActivitySearchTool.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/tool/ExpediaCarRentalSearchTool.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/tool/ExpediaDestinationInfoTool.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/tool/ExpediaFlightSearchTool.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/tool/ExpediaHotelDetailsTool.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/java/com/alibaba/langengine/expedia/tool/ExpediaHotelSearchTool.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/main/resources/META-INF/services/com.alibaba.langengine.core.tool.BaseTool
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/test/java/com/alibaba/langengine/expedia/ExpediaExamples.java
ali-langengine/ali-langengine-community/ali-langengine-expedia/src/test/java/com/alibaba/langengine/expedia/ExpediaToolsTest.java

Add Expedia tools for hotel, flight, car rental, and activity searches

---

ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/pom.xml
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/TencentVdbConfiguration.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/config/DefaultTencentVdbConfig.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/config/TencentVdbConfig.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdb.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbClient.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbException.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbParam.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbService.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/main/java/com/alibaba/langengine/tencentvdb/vectorstore/VectorDbClient.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/test/java/com/alibaba/langengine/tencentvdb/test/TestUtils.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/test/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbClientTest.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/test/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbServiceTest.java
ali-langengine/ali-langengine-community/ali-langengine-tencentvdb/src/test/java/com/alibaba/langengine/tencentvdb/vectorstore/TencentVdbTest.java
ali-langengine/pom.xml

feat(vectorstore): add TencentVdb
